# Generated by Django 5.2 on 2025-04-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_False',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
